import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from 'antd';

import Navigation from "@/components/Navigation";
import FooterComponent from "@/components/Footer";
import AppProvider from "@/components/AppProvider";
import { AuthProvider } from "./context/AuthContext";
import AntdAppProvider from "@/components/AppProvider";
const { Content } = Layout;
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Ordering App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js">
      <body className={inter.className}>
            <AuthProvider>
        <AntdRegistry>
      <AntdAppProvider>
            <AppProvider>
            <Layout style={{ minHeight: '100vh' }}>
            <Navigation /> 
          
              <div style={{ background: '#fff', padding: 24, minHeight: 280 }}>
                {children} 
              </div>
            <FooterComponent />
          </Layout>
          </AppProvider>
</AntdAppProvider>
        </AntdRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}