import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientLayout from "@/components/ClientLayout";

// import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({ subsets: ["latin"] });

// Giữ lại metadata ở đây, vì đây là Server Component
export const metadata: Metadata = {
  title: "Food ordering service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}